# Generated by Django 4.0.4 on 2022-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='conversion_ratio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
