# Generated by Django 4.0.4 on 2022-05-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_produtmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtmodel',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.unitmodel'),
            preserve_default=False,
        ),
    ]
