# Generated by Django 4.0.4 on 2022-05-05 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_produtmodel_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtmodel',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produtmodel',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
