# Generated by Django 4.0.4 on 2022-05-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
