# Generated by Django 4.0.4 on 2022-05-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='phone_no',
            field=models.CharField(default=0, max_length=14),
        ),
    ]
